import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Docs",
    description: "Generated by create next app",
};

export default function DocsPage() {
    return (
        <div className="prose prose-slate dark:prose-invert max-w-none">
            <h1 className="text-4xl font-bold mb-4 text-foreground">Introduction</h1>
            <p className="text-lg text-slate-500 mb-8">
                Welcome to DB Designer. This tool was built to bridge the gap between whiteboard sketching and production-ready database architecture.
            </p>

            <h2 className="text-2xl font-bold mb-4 mt-12 text-foreground">Why use a visual schema builder?</h2>
            <p className="text-slate-500 mb-4">
                Writing DDL (Data Definition Language) by hand is prone to syntax errors, missing foreign keys, and overlapping relationships. DB Designer enforces strict rules—like ensuring every entity has a Primary Key—before you ever run a migration.
            </p>

            <div className="bg-surface border border-surface-border rounded-lg p-6 my-8">
                <h3 className="font-bold mb-2">💡 Pro Tip</h3>
                <p className="text-sm text-slate-400 m-0">
                    You can instantly generate Prisma Schema syntax or raw MySQL directly from your canvas by clicking the "Generate SQL" button in the top right of your workspace.
                </p>
            </div>

            {/* Add more markdown-style content here as needed! */}
        </div>
    );
}