// lib/prismaGenerator.ts
import { preProcessRelationships } from './sqlGenerator';

const mapPrismaType = (sqlType: string) => {
    const type = (sqlType || 'VARCHAR').toUpperCase();
    if (type.includes('INT')) return 'Int';
    if (type.includes('BOOL') || type.includes('BIT')) return 'Boolean';
    if (type.includes('DATE') || type.includes('TIME')) return 'DateTime';
    if (type.includes('FLOAT') || type.includes('DECIMAL') || type.includes('DOUBLE')) return 'Float';
    return 'String';
};

const pluralize = (word: string) => {
    if (!word) return 'items';
    const lower = word.toLowerCase();
    if (lower.endsWith('ch') || lower.endsWith('s') || lower.endsWith('x') || lower.endsWith('sh')) return lower + 'es';
    if (lower.endsWith('y') && !/[aeiou]y$/.test(lower)) return lower.slice(0, -1) + 'ies';
    return lower + 's';
};

export const generatePrisma = (
    compiledEntities: any[],
    edges: any[],
    relationshipAttributes: any[] = []
) => {
    let schema = `// Generated by DB Designer\n\n`;
    schema += `generator client {\n  provider = "prisma-client-js"\n}\n\n`;
    schema += `datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`;

    const processedEntities = preProcessRelationships(compiledEntities, edges, relationshipAttributes);

    const modelRelations: Record<string, string[]> = {};
    const usedModelFields: Record<string, Set<string>> = {};
    const globalUsedRelationTags = new Set<string>();

    const getUniqueField = (model: string, baseName: string) => {
        if (!usedModelFields[model]) usedModelFields[model] = new Set();
        let finalName = baseName;
        let counter = 1;
        while (usedModelFields[model].has(finalName)) {
            finalName = `${baseName}_${counter++}`;
        }
        usedModelFields[model].add(finalName);
        return finalName;
    };

    processedEntities.forEach((e: any) => {
        usedModelFields[e.data.label] = new Set();
        modelRelations[e.data.label] = [];
        e.attributes.forEach((a: any) => {
            const n = a.name || a.data?.label;
            if (n) usedModelFields[e.data.label].add(n);
        });
    });

    // 🌟 COUNT ENGINE: Count ALL physical connections between tables to strictly detect ambiguity
    const relationCount: Record<string, number> = {};
    processedEntities.forEach(e => {
        if (e.foreignKeys) {
            e.foreignKeys.forEach((fk: any) => {
                // Sort the table names so A->B and B->A resolve to the same collision pool
                const pairKey = [e.data.label, fk.referencesTable].sort().join('_');
                relationCount[pairKey] = (relationCount[pairKey] || 0) + 1;
            });
        }
    });

    // 🌟 1. Semantic M:N (Junctions)
    const finalEntities = processedEntities.filter((entity: any) => {
        if (String(entity.id).startsWith('junction_')) {
            const fk1 = entity.foreignKeys[0];
            const fk2 = entity.foreignKeys[1];
            const tableA = fk1.referencesTable;
            const tableB = fk2.referencesTable;

            const edgeId = String(entity.id).replace('junction_', '');
            const originalEdge = edges.find(e => String(e.id) === edgeId);

            const edgeLabel = String(originalEdge?.data?.label || '').replace(/[^a-zA-Z0-9_]/g, '');

            const prefix = edgeLabel ? `${edgeLabel.toLowerCase()}_` : '';
            const arrA = getUniqueField(tableA, `${prefix}${pluralize(tableB)}`);
            const arrB = getUniqueField(tableB, `${prefix}${pluralize(tableA)}`);

            // M:N always gets a tag because Prisma uses it to physically name the junction table in the DB
            let finalRelTag = edgeLabel ? edgeLabel.toUpperCase() : `${tableA}_${tableB}`;
            let rCount = 1;
            while (globalUsedRelationTags.has(finalRelTag)) { finalRelTag = `${finalRelTag}_${rCount++}`; }
            globalUsedRelationTags.add(finalRelTag);

            modelRelations[tableA].push(`  ${arrA} ${tableB}[] @relation("${finalRelTag}")`);
            modelRelations[tableB].push(`  ${arrB} ${tableA}[] @relation("${finalRelTag}")`);

            // what's this?
            if (entity.attributes && entity.attributes.length > 0) {
                // It has payload data! Prisma requires explicit junction models for payload data.
                return true; 
            }

            return false;
        }
        return true;
    });

    // 🌟 2. Semantic 1:N
    finalEntities.forEach((entity: any) => {
        if (entity.foreignKeys) {
            entity.foreignKeys.forEach((fk: any) => {
                const targetTable = fk.referencesTable;
                const sourceTable = entity.data.label;

                const edgeLabel = String(fk.edgeLabel || '').replace(/[^a-zA-Z0-9_]/g, '');
                const prefix = edgeLabel ? `${edgeLabel.toLowerCase()}_` : '';

                fk.uniqueScalarName = getUniqueField(sourceTable, fk.name);
                fk.uniqueObjectName = getUniqueField(sourceTable, `${prefix}${targetTable.toLowerCase()}`);

                const arrName = getUniqueField(targetTable, `${prefix}${pluralize(sourceTable)}`);

                // 🌟 THE FAANG FIX: Only add the @relation("...") string if there are multiple lines connecting these two exact tables!
                const pairKey = [sourceTable, targetTable].sort().join('_');
                const isAmbiguous = relationCount[pairKey] > 1;

                if (isAmbiguous) {
                    let finalRelTag = edgeLabel ? edgeLabel.toUpperCase() : `${sourceTable}_${targetTable}`;
                    let rCount = 1;
                    while (globalUsedRelationTags.has(finalRelTag)) { finalRelTag = `${finalRelTag}_${rCount++}`; }
                    globalUsedRelationTags.add(finalRelTag);
                    fk.relationString = `"${finalRelTag}"`;
                } else {
                    // No ambiguity? Omit the string completely. Prisma handles it implicitly.
                    fk.relationString = null;
                }

                const relStr = fk.relationString ? ` @relation(${fk.relationString})` : '';
                modelRelations[targetTable].push(`  ${arrName} ${sourceTable}[]${relStr}`);
            });
        }
    });

    // 3. Code Output
    finalEntities.forEach((entity: any) => {
        schema += `model ${entity.data.label} {\n`;

        entity.attributes.forEach((rawAttr: any) => {
            const name = rawAttr.name || rawAttr.data?.label;
            const rawType = String(rawAttr.attributeType || rawAttr.data?.attributeType || '').toLowerCase().replace(/[^a-z]/g, '');

            if (rawType === 'derived') {
                schema += `  // Note: '${name}' is a derived attribute.\n`;
                return;
            }

            const type = mapPrismaType(rawAttr.dataType || rawAttr.data?.dataType);
            const isPK = (entity.data.primaryKey === name || entity.data.primaryKey === rawAttr.id) && entity.data.primaryKey !== 'COMPOSITE';
            const isPartofCompositePK = entity.compositePK && entity.compositePK.includes(name);
            const isNotNull = rawAttr.isNotNull || rawAttr.data?.isNotNull;

            const isOptional = (!isNotNull && !isPK && !isPartofCompositePK) ? "?" : "";
            const isUnique = (rawAttr.isUnique || rawAttr.data?.isUnique) && !isPK && !isPartofCompositePK ? " @unique" : "";

            schema += `  ${name} ${type}${isOptional}${isPK ? ' @id' : ''}${isUnique}\n`;
        });

        if (entity.foreignKeys) {
            entity.foreignKeys.forEach((fk: any) => {
                const type = mapPrismaType(fk.dataType);
                schema += `\n  ${fk.uniqueScalarName} ${type}\n`;

                // If relationString is null, this outputs a beautifully clean: @relation(fields: [...], references: [...])
                const relTag = fk.relationString ? `${fk.relationString}, ` : "";
                schema += `  ${fk.uniqueObjectName} ${fk.referencesTable} @relation(${relTag}fields: [${fk.uniqueScalarName}], references: [${fk.referencesCol}])\n`;
            });
        }

        const tableRels = modelRelations[entity.data.label];
        if (tableRels && tableRels.length > 0) {
            schema += `\n  // Relations\n`;
            tableRels.forEach(rel => { schema += `${rel}\n`; });
        }

        if (entity.compositePK && entity.compositePK.length > 0) {
            schema += `\n  @@id([${entity.compositePK.join(', ')}])\n`;
        }

        schema += `}\n\n`;
    });

    return schema;
};