// lib/prismaGenerator.ts
import { preProcessRelationships } from './sqlGenerator';

const mapPrismaType = (sqlType: string) => {
    const type = (sqlType || 'VARCHAR').toUpperCase();
    if (type.includes('INT')) return 'Int';
    if (type.includes('BOOL')) return 'Boolean';
    if (type.includes('DATE') || type.includes('TIME')) return 'DateTime';
    if (type.includes('FLOAT') || type.includes('DOUBLE')) return 'Float';
    if (type.includes('DECIMAL')) return 'Decimal';
    return 'String';
};

export const generatePrisma = (compiledEntities: any[], edges: any[]) => {
    let schema = `// Generated by DB Designer\n\n`;
    schema += `generator client {\n  provider = "prisma-client-js"\n}\n\n`;
    schema += `datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`;

    const processedEntities = preProcessRelationships(compiledEntities, edges);
    const backRelations: Record<string, string[]> = {};

    processedEntities.forEach((entity: any) => {
        if (entity.foreignKeys && entity.foreignKeys.length > 0) {
            entity.foreignKeys.forEach((fk: any) => {
                const targetTable = fk.referencesTable;
                const sourceTable = entity.data.label;

                if (!backRelations[targetTable]) backRelations[targetTable] = [];

                let fieldName = sourceTable.toLowerCase();
                if (fieldName.endsWith('ch') || fieldName.endsWith('s') || fieldName.endsWith('x')) {
                    fieldName += 'es';
                } else if (fieldName.endsWith('y')) {
                    fieldName = fieldName.slice(0, -1) + 'ies';
                } else {
                    fieldName += 's';
                }

                let finalFieldName = fieldName;
                let counter = 1;
                while (backRelations[targetTable].some(rel => rel.startsWith(`  ${finalFieldName} `))) {
                    finalFieldName = `${fieldName}_${counter}`;
                    counter++;
                }

                backRelations[targetTable].push(`  ${finalFieldName} ${sourceTable}[]`);
            });
        }
    });

    processedEntities.forEach((entity: any) => {
        schema += `model ${entity.data.label} {\n`;

        entity.attributes.forEach((rawAttr: any) => {
            const name = rawAttr.name || rawAttr.data?.label;

            const rawType = String(rawAttr.attributeType || rawAttr.data?.attributeType || '').toLowerCase().replace(/[^a-z]/g, '');
            if (rawType === 'derived') {
                schema += `  // Note: '${name}' is a derived attribute.\n`;
                return;
            }

            const type = mapPrismaType(rawAttr.dataType || rawAttr.data?.dataType);

            const isPK = (entity.data.primaryKey === name || entity.data.primaryKey === rawAttr.id) && entity.data.primaryKey !== 'COMPOSITE';

            // Ensure Composite PK components are NEVER marked optional
            const isPartofCompositePK = entity.compositePK && entity.compositePK.includes(name);
            const isNotNull = rawAttr.isNotNull || rawAttr.data?.isNotNull;

            // If it's a primary key (standard or composite) or explicitly marked Not Null, it cannot be optional.
            const isOptional = (!isNotNull && !isPK && !isPartofCompositePK) ? "?" : "";

            // Composite PK components don't need individual @unique tags
            const isUnique = (rawAttr.isUnique || rawAttr.data?.isUnique) && !isPK && !isPartofCompositePK ? " @unique" : "";

            schema += `  ${name} ${type}${isOptional}${isPK ? ' @id' : ''}${isUnique}\n`;
        });

        if (entity.foreignKeys && entity.foreignKeys.length > 0) {
            entity.foreignKeys.forEach((fk: any) => {
                const type = mapPrismaType(fk.dataType);
                schema += `  ${fk.name} ${type}\n`;
                const relationObjectName = fk.referencesTable.toLowerCase();
                schema += `  ${relationObjectName} ${fk.referencesTable} @relation(fields: [${fk.name}], references: [${fk.referencesCol}])\n`;
            });
        }

        const tableBackRels = backRelations[entity.data.label];
        if (tableBackRels && tableBackRels.length > 0) {
            schema += `\n  // Back-relations\n`;
            tableBackRels.forEach(rel => { schema += `${rel}\n`; });
        }

        if (entity.compositePK && entity.compositePK.length > 0) {
            schema += `\n  @@id([${entity.compositePK.join(', ')}])\n`;
        }

        schema += `}\n\n`;
    });

    return schema;
};