// lib/prismaGenerator.ts
import { preProcessRelationships } from './sqlGenerator';

const mapPrismaType = (sqlType: string) => {
    const type = (sqlType || 'VARCHAR').toUpperCase();
    if (type.includes('INT')) return 'Int';
    if (type.includes('BOOL') || type.includes('BIT')) return 'Boolean';
    if (type.includes('DATE') || type.includes('TIME')) return 'DateTime';
    if (type.includes('FLOAT') || type.includes('DECIMAL') || type.includes('DOUBLE')) return 'Float';
    return 'String';
};

export const generatePrisma = (compiledEntities: any[], edges: any[]) => {
    let schema = `// Generated by DB Designer\n\n`;
    schema += `generator client {\n  provider = "prisma-client-js"\n}\n\n`;
    schema += `datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`;

    const processedEntities = preProcessRelationships(compiledEntities, edges);

    processedEntities.forEach((entity: any) => {
        schema += `model ${entity.data.label} {\n`;

        // 1. Standard Attributes
        entity.attributes.forEach((rawAttr: any) => {
            const name = rawAttr.name || rawAttr.data?.label;

            // 🌟 Robust Derived Attribute Logic
            const rawType = String(rawAttr.attributeType || rawAttr.data?.attributeType || '').toLowerCase().replace(/[^a-z]/g, '');
            if (rawType === 'derived') {
                schema += `  // Note: '${name}' is a derived attribute.\n`;
                return;
            }

            const type = mapPrismaType(rawAttr.dataType || rawAttr.data?.dataType);
            const isPK = (entity.data.primaryKey === name || entity.data.primaryKey === rawAttr.id) && entity.data.primaryKey !== 'COMPOSITE';
            
            schema += `  ${name} ${type}${isPK ? ' @id' : ''}\n`;
        });

        // 2. Foreign Keys & Relations
        if (entity.foreignKeys && entity.foreignKeys.length > 0) {
            entity.foreignKeys.forEach((fk: any) => {
                const type = mapPrismaType(fk.dataType);
                schema += `  ${fk.name} ${type}\n`; 
                const relationObjectName = fk.referencesTable.toLowerCase();
                schema += `  ${relationObjectName} ${fk.referencesTable} @relation(fields: [${fk.name}], references: [${fk.referencesCol}])\n`;
            });
        }

        // 3. Composite Primary Keys
        if (entity.compositePK && entity.compositePK.length > 0) {
            schema += `\n  @@id([${entity.compositePK.join(', ')}])\n`;
        }

        schema += `}\n\n`;
    });

    return schema;
};