// lib/sqlGenerator.ts

// 🌟 1. The Normalizer: Extracts data perfectly whether it's a visual node or hidden attribute
const getPKDetails = (entity: any) => {
    const pkIdentifier = entity.data?.primaryKey;
    if (!pkIdentifier) return null;

    // Find the raw attribute object
    const rawAttr = entity.attributes.find((attr: any) => attr.id === pkIdentifier || attr.name === pkIdentifier);
    if (!rawAttr) return null;

    // Return a perfectly flat, predictable object
    return {
        name: rawAttr.name || rawAttr.data?.label,
        dataType: rawAttr.dataType || rawAttr.data?.dataType,
        size: rawAttr.size || rawAttr.data?.size
    };
};

const preProcessRelationships = (compiledEntities: any[], edges: any[]) => {
    // Deep copy and initialize empty foreignKeys array
    let processedEntities = compiledEntities.map(e => ({ ...e, foreignKeys: [] }));
    const relationshipEdges = edges.filter(e => e.type === 'relationship');

    relationshipEdges.forEach(edge => {
        const sourceNode = processedEntities.find(n => n.id === edge.source);
        const targetNode = processedEntities.find(n => n.id === edge.target);

        if (!sourceNode || !targetNode) return;

        // 🌟 2. Fixed Defaults: Must match your UI components exactly!
        const sourceMax = edge.data?.sourceMaximumCardinality || 'M';
        const targetMax = edge.data?.targetMaximumCardinality || 'N';

        const sourcePK = getPKDetails(sourceNode);
        const targetPK = getPKDetails(targetNode);

        if (!sourcePK || !targetPK) return;

        // SCENARIO 1: Many-to-Many (M:N) -> Create a Junction Table
        if ((sourceMax === 'M' || sourceMax === 'N') && (targetMax === 'M' || targetMax === 'N')) {
            const relName = edge.data?.label && edge.data.label !== 'REL' ? `_${edge.data.label}_` : '_';
            const junctionName = `${sourceNode.data.label}${relName}${targetNode.data.label}`;

            const junctionTable = {
                id: `junction_${edge.id}`,
                data: { label: junctionName.toUpperCase(), primaryKey: 'COMPOSITE' },
                attributes: [],
                foreignKeys: [
                    {
                        name: `${sourceNode.data.label.toLowerCase()}_${sourcePK.name}`,
                        dataType: sourcePK.dataType, size: sourcePK.size,
                        referencesTable: sourceNode.data.label, referencesCol: sourcePK.name,
                        isJunctionPK: true
                    },
                    {
                        name: `${targetNode.data.label.toLowerCase()}_${targetPK.name}`,
                        dataType: targetPK.dataType, size: targetPK.size,
                        referencesTable: targetNode.data.label, referencesCol: targetPK.name,
                        isJunctionPK: true
                    }
                ]
            };
            processedEntities.push(junctionTable);
            return;
        }

        // SCENARIO 2: Unary (Self-Referencing 1:N or 1:1)
        if (edge.source === edge.target) {
            const relName = edge.data?.label && edge.data.label !== 'REL' ? edge.data.label.toLowerCase() : 'parent';
            sourceNode.foreignKeys.push({
                name: `${relName}_${sourcePK.name}`,
                dataType: sourcePK.dataType, size: sourcePK.size,
                referencesTable: sourceNode.data.label, referencesCol: sourcePK.name
            });
            return;
        }

        // SCENARIO 3: Binary 1:N, N:1, or 1:1
        let receivingNode, referencingNode, referencingPK;

        if (sourceMax === '1' && (targetMax === 'N' || targetMax === 'M')) {
            receivingNode = targetNode; referencingNode = sourceNode; referencingPK = sourcePK;
        } else if ((sourceMax === 'M' || sourceMax === 'N') && targetMax === '1') {
            receivingNode = sourceNode; referencingNode = targetNode; referencingPK = targetPK;
        } else {
            receivingNode = targetNode; referencingNode = sourceNode; referencingPK = sourcePK;
        }

        receivingNode.foreignKeys.push({
            name: `${referencingNode.data.label.toLowerCase()}_${referencingPK.name}`,
            dataType: referencingPK.dataType, size: referencingPK.size,
            referencesTable: referencingNode.data.label, referencesCol: referencingPK.name
        });
    });

    return processedEntities;
};

export const generateMySQL = (compiledEntities: any[], edges: any[]) => {
    let sqlScript = `-- Generated by DB Designer\n\n`;
    const processedEntities = preProcessRelationships(compiledEntities, edges);

    processedEntities.forEach((entity) => {
        sqlScript += buildTableSQL(entity);
    });

    return sqlScript;
};

const buildTableSQL = (entity: any) => {
    let tableScript = `CREATE TABLE ${entity.data.label} (\n`;
    const constraints: string[] = [];

    // 🌟 3. Normalize Standard Attributes inline
    const columnDefinitions = entity.attributes.map((rawAttr: any) => {
        const name = rawAttr.name || rawAttr.data?.label;
        const dataType = rawAttr.dataType || rawAttr.data?.dataType;
        const size = rawAttr.size || rawAttr.data?.size;

        const sizeStr = size ? `(${size})` : "";
        const isPK = entity.data.primaryKey === rawAttr.name || entity.data.primaryKey === rawAttr.id;
        const pkStr = isPK ? " PRIMARY KEY" : "";

        return `    ${name} ${dataType}${sizeStr}${pkStr}`;
    });

    // Foreign Key Attributes (These are already perfectly flat from our preProcessor)
    if (entity.foreignKeys && entity.foreignKeys.length > 0) {
        entity.foreignKeys.forEach((fk: any) => {
            const sizeStr = fk.size ? `(${fk.size})` : "";
            // Push the FK column itself
            columnDefinitions.push(`    ${fk.name} ${fk.dataType}${sizeStr}`);
            // Push the relational constraint
            constraints.push(`    FOREIGN KEY (${fk.name}) REFERENCES ${fk.referencesTable}(${fk.referencesCol})`);
        });

        // Handle Composite Primary Keys for M:N Junction Tables
        const junctionPKs = entity.foreignKeys.filter((fk: any) => fk.isJunctionPK).map((fk: any) => fk.name);
        if (junctionPKs.length > 0) {
            constraints.unshift(`    PRIMARY KEY (${junctionPKs.join(', ')})`);
        }
    }

    // Combine columns and constraints cleanly
    const allTableLines = [...columnDefinitions, ...constraints];
    tableScript += allTableLines.join(',\n');
    tableScript += `\n);\n\n`;

    return tableScript;
}