// lib/sqlGenerator.ts

export type SQLDialect = 'mysql' | 'oracle';

// 🌟 1. The Data Type Mapper (The Strategy Engine)
const mapDataType = (dataType: string, dialect: SQLDialect) => {
    const upperType = (dataType || 'VARCHAR').toUpperCase();

    if (dialect === 'mysql') return upperType;

    // Oracle specific type mappings
    if (dialect === 'oracle') {
        if (upperType === 'VARCHAR') return 'VARCHAR2';
        if (upperType === 'INT' || upperType === 'INTEGER') return 'NUMBER';
        if (upperType === 'DATETIME') return 'TIMESTAMP';
        if (upperType === 'TEXT') return 'CLOB';
    }

    return upperType;
};

// 🌟 2. The Normalizer (Unchanged)
const getPKDetails = (entity: any) => {
    const pkIdentifier = entity.data?.primaryKey;
    if (!pkIdentifier) return null;

    const rawAttr = entity.attributes.find((attr: any) => attr.id === pkIdentifier || attr.name === pkIdentifier);
    if (!rawAttr) return null;

    return {
        name: rawAttr.name || rawAttr.data?.label,
        dataType: rawAttr.dataType || rawAttr.data?.dataType,
        size: rawAttr.size || rawAttr.data?.size
    };
};

// 🌟 3. The Relationship Pre-Processor (Unchanged)
export const preProcessRelationships = (compiledEntities: any[], edges: any[]) => {
    let processedEntities = compiledEntities.map(e => ({ ...e, foreignKeys: [] }));
    const relationshipEdges = edges.filter(e => e.type === 'relationship');

    relationshipEdges.forEach(edge => {
        const sourceNode = processedEntities.find(n => n.id === edge.source);
        const targetNode = processedEntities.find(n => n.id === edge.target);

        if (!sourceNode || !targetNode) return;

        const sourceMax = edge.data?.sourceMaximumCardinality || 'M';
        const targetMax = edge.data?.targetMaximumCardinality || 'N';

        const sourcePK = getPKDetails(sourceNode);
        const targetPK = getPKDetails(targetNode);

        if (!sourcePK || !targetPK) return;

        // SCENARIO 1: Many-to-Many (M:N)
        if ((sourceMax === 'M' || sourceMax === 'N') && (targetMax === 'M' || targetMax === 'N')) {
            const relName = edge.data?.label && edge.data.label !== 'REL' ? `_${edge.data.label}_` : '_';
            const junctionName = `${sourceNode.data.label}${relName}${targetNode.data.label}`;

            const junctionTable = {
                id: `junction_${edge.id}`,
                data: { label: junctionName.toUpperCase(), primaryKey: 'COMPOSITE' },
                attributes: [],
                foreignKeys: [
                    {
                        name: `${sourceNode.data.label.toLowerCase()}_${sourcePK.name}`,
                        dataType: sourcePK.dataType, size: sourcePK.size,
                        referencesTable: sourceNode.data.label, referencesCol: sourcePK.name,
                        isJunctionPK: true
                    },
                    {
                        name: `${targetNode.data.label.toLowerCase()}_${targetPK.name}`,
                        dataType: targetPK.dataType, size: targetPK.size,
                        referencesTable: targetNode.data.label, referencesCol: targetPK.name,
                        isJunctionPK: true
                    }
                ]
            };
            processedEntities.push(junctionTable);
            return;
        }

        // SCENARIO 2: Unary (Self-Referencing 1:N or 1:1)
        if (edge.source === edge.target) {
            const relName = edge.data?.label && edge.data.label !== 'REL' ? edge.data.label.toLowerCase() : 'parent';
            sourceNode.foreignKeys.push({
                name: `${relName}_${sourcePK.name}`,
                dataType: sourcePK.dataType, size: sourcePK.size,
                referencesTable: sourceNode.data.label, referencesCol: sourcePK.name
            });
            return;
        }

        // SCENARIO 3: Binary 1:N, N:1, or 1:1
        let receivingNode, referencingNode, referencingPK;

        if (sourceMax === '1' && (targetMax === 'N' || targetMax === 'M')) {
            receivingNode = targetNode; referencingNode = sourceNode; referencingPK = sourcePK;
        } else if ((sourceMax === 'M' || sourceMax === 'N') && targetMax === '1') {
            receivingNode = sourceNode; referencingNode = targetNode; referencingPK = targetPK;
        } else {
            receivingNode = targetNode; referencingNode = sourceNode; referencingPK = sourcePK;
        }

        receivingNode.foreignKeys.push({
            name: `${referencingNode.data.label.toLowerCase()}_${referencingPK.name}`,
            dataType: referencingPK.dataType, size: referencingPK.size,
            referencesTable: referencingNode.data.label, referencesCol: referencingPK.name
        });
    });

    return processedEntities;
};

// 🌟 4. The Master Generator Function
export const generateSQL = (compiledEntities: any[], edges: any[], dialect: SQLDialect = 'mysql') => {
    let sqlScript = `-- Generated by DB Designer\n`;
    sqlScript += `-- Dialect: ${dialect === 'oracle' ? 'Oracle SQL' : 'MySQL'}\n\n`;

    const processedEntities = preProcessRelationships(compiledEntities, edges);

    processedEntities.forEach((entity) => {
        sqlScript += buildTableSQL(entity, dialect);
    });

    return sqlScript;
};

// 🌟 5. The Dialect-Aware Table Builder
const buildTableSQL = (entity: any, dialect: SQLDialect) => {
    let tableScript = `CREATE TABLE ${entity.data.label} (\n`;
    const constraints: string[] = [];

    const columnDefinitions: string[] = entity.attributes.map((rawAttr: any) => {
        const name = rawAttr.name || rawAttr.data?.label;
        const rawDataType = rawAttr.dataType || rawAttr.data?.dataType;
        const mappedDataType = mapDataType(rawDataType, dialect);

        let size = rawAttr.size || rawAttr.data?.size;

        // Fallback size for VARCHAR/VARCHAR2 if the user forgot it (Oracle strictly requires it)
        if (!size && (mappedDataType === 'VARCHAR2' || mappedDataType === 'VARCHAR')) {
            size = '255';
        }

        const sizeStr = size ? `(${size})` : "";
        const isPK = entity.data.primaryKey === rawAttr.name || entity.data.primaryKey === rawAttr.id;
        const pkStr = isPK ? " PRIMARY KEY" : "";

        return `    ${name} ${mappedDataType}${sizeStr}${pkStr}`;
    });

    if (entity.foreignKeys && entity.foreignKeys.length > 0) {
        entity.foreignKeys.forEach((fk: any) => {
            const mappedFkType = mapDataType(fk.dataType, dialect);

            let size = fk.size;
            if (!size && (mappedFkType === 'VARCHAR2' || mappedFkType === 'VARCHAR')) size = '255';
            const sizeStr = size ? `(${size})` : "";

            columnDefinitions.push(`    ${fk.name} ${mappedFkType}${sizeStr}`);
            constraints.push(`    FOREIGN KEY (${fk.name}) REFERENCES ${fk.referencesTable}(${fk.referencesCol})`);
        });

        const junctionPKs = entity.foreignKeys.filter((fk: any) => fk.isJunctionPK).map((fk: any) => fk.name);
        if (junctionPKs.length > 0) {
            constraints.unshift(`    PRIMARY KEY (${junctionPKs.join(', ')})`);
        }
    }

    const allTableLines = [...columnDefinitions, ...constraints];
    tableScript += allTableLines.join(',\n');
    tableScript += `\n);\n\n`;

    return tableScript;
}