// lib/sqlGenerator.ts

// Helper function to find the full Attribute object using the normalized PK string
const getPKDetails = (entity: any) => {
    const pkIdentifier = entity.data?.primaryKey;
    if (!pkIdentifier) return null;
    // Search the flattened attributes array for the matching name or ID
    return entity.attributes.find((attr: any) => attr.name === pkIdentifier || attr.id === pkIdentifier);
};

const preProcessRelationships = (compiledEntities: any[], edges: any[]) => {
    // 1. Deep copy the entities so we don't mutate the Zustand store directly, 
    // and initialize an empty foreignKeys array on every table.
    let processedEntities = compiledEntities.map(e => ({ ...e, foreignKeys: [] }));

    const relationshipEdges = edges.filter(e => e.type === 'relationship');

    relationshipEdges.forEach(edge => {
        const sourceNode = processedEntities.find(n => n.id === edge.source);
        const targetNode = processedEntities.find(n => n.id === edge.target);

        if (!sourceNode || !targetNode) return;

        // Safely extract cardinalities (defaulting to 1 and N if missing)
        const sourceMax = edge.data?.sourceMaximumCardinality || '1';
        const targetMax = edge.data?.targetMaximumCardinality || 'N';

        const sourcePK = getPKDetails(sourceNode);
        const targetPK = getPKDetails(targetNode);

        if (!sourcePK || !targetPK) return; // Skip if a table is missing a PK

        // SCENARIO 1: Many-to-Many (M:N) -> Create a Junction Table!
        if ((sourceMax === 'M' || sourceMax === 'N') && (targetMax === 'M' || targetMax === 'N')) {
            // Name it dynamically based on the relationship name (e.g., STUDENT_ENROLLS_COURSE)
            const relName = edge.data?.label && edge.data.label !== 'REL' ? `_${edge.data.label}_` : '_';
            const junctionName = `${sourceNode.data.label}${relName}${targetNode.data.label}`;

            const junctionTable = {
                id: `junction_${edge.id}`,
                data: { label: junctionName.toUpperCase(), primaryKey: 'COMPOSITE' },
                attributes: [], // No standard attributes
                foreignKeys: [
                    {
                        name: `${sourceNode.data.label.toLowerCase()}_${sourcePK.name}`,
                        dataType: sourcePK.dataType, size: sourcePK.size,
                        referencesTable: sourceNode.data.label, referencesCol: sourcePK.name,
                        isJunctionPK: true
                    },
                    {
                        name: `${targetNode.data.label.toLowerCase()}_${targetPK.name}`,
                        dataType: targetPK.dataType, size: targetPK.size,
                        referencesTable: targetNode.data.label, referencesCol: targetPK.name,
                        isJunctionPK: true
                    }
                ]
            };
            processedEntities.push(junctionTable);
            return;
        }

        // SCENARIO 2: Unary (Self-Referencing 1:N or 1:1)
        if (edge.source === edge.target) {
            const relName = edge.data?.label && edge.data.label !== 'REL' ? edge.data.label.toLowerCase() : 'parent';
            sourceNode.foreignKeys.push({
                name: `${relName}_${sourcePK.name}`, // e.g., 'manager_emp_id'
                dataType: sourcePK.dataType, size: sourcePK.size,
                referencesTable: sourceNode.data.label, referencesCol: sourcePK.name
            });
            return;
        }

        // SCENARIO 3: Binary 1:N, N:1, or 1:1
        let receivingNode, referencingNode, referencingPK;

        if (sourceMax === '1' && (targetMax === 'N' || targetMax === 'M')) {
            // 1:N -> Target gets the FK
            receivingNode = targetNode; referencingNode = sourceNode; referencingPK = sourcePK;
        } else if ((sourceMax === 'M' || sourceMax === 'N') && targetMax === '1') {
            // N:1 -> Source gets the FK
            receivingNode = sourceNode; referencingNode = targetNode; referencingPK = targetPK;
        } else {
            // 1:1 -> Arbitrarily put it in the target to keep it simple
            receivingNode = targetNode; referencingNode = sourceNode; referencingPK = sourcePK;
        }

        receivingNode.foreignKeys.push({
            name: `${referencingNode.data.label.toLowerCase()}_${referencingPK.name}`, // e.g., 'department_dept_id'
            dataType: referencingPK.dataType, size: referencingPK.size,
            referencesTable: referencingNode.data.label, referencesCol: referencingPK.name
        });
    });

    return processedEntities;
};


export const generateMySQL = (compiledEntities: any[], edges: any[]) => {
    let sqlScript = `-- Generated by DB Designer\n\n`;

    // 1. Run the Pre-Processor first!
    const processedEntities = preProcessRelationships(compiledEntities, edges);

    // 2. Build the tables using the processed array
    processedEntities.forEach((entity) => {
        sqlScript += buildTableSQL(entity);
    });

    return sqlScript;
};

const buildTableSQL = (entity: any) => {
    let tableScript = `CREATE TABLE ${entity.data.label} (\n`;
    const constraints: string[] = [];

    // 1. Standard Attributes
    const columnDefinitions = entity.attributes.map((attr: any) => {
        const sizeStr = attr.size ? `(${attr.size})` : "";
        const isPK = entity.data.primaryKey === attr.name || entity.data.primaryKey === attr.id;
        const pkStr = isPK ? " PRIMARY KEY" : "";
        return `    ${attr.name} ${attr.dataType}${sizeStr}${pkStr}`;
    });

    // 2. Foreign Key Attributes
    if (entity.foreignKeys && entity.foreignKeys.length > 0) {
        entity.foreignKeys.forEach((fk: any) => {
            const sizeStr = fk.size ? `(${fk.size})` : "";
            columnDefinitions.push(`    ${fk.name} ${fk.dataType}${sizeStr}`);

            // Generate the actual relational constraint
            constraints.push(`    FOREIGN KEY (${fk.name}) REFERENCES ${fk.referencesTable}(${fk.referencesCol})`);
        });

        // 3. Handle Composite Primary Keys for M:N Junction Tables
        const junctionPKs = entity.foreignKeys.filter((fk: any) => fk.isJunctionPK).map((fk: any) => fk.name);
        if (junctionPKs.length > 0) {
            constraints.unshift(`    PRIMARY KEY (${junctionPKs.join(', ')})`);
        }
    }

    // Combine columns and constraints
    const allTableLines = [...columnDefinitions, ...constraints];
    tableScript += allTableLines.join(',\n');
    tableScript += `\n);\n\n`;

    return tableScript;
}