import { StateGraph, START, END } from "@langchain/langgraph";
import { getResilientStructuredModel, resilientModel } from "./model";
import { AgentState } from "./state";
import {
  AgentDiagramSchema,
  AgentDiagramSchemaBase,
  ScriptValidationSchema,
} from "./schemas";
import z from "zod";
import { traceable } from "langsmith/traceable";
import { SQL_RESERVED_WORDS } from "@/lib/schema";

// PHASE 1:

// 1. The Generator Node
/**
 * Generator Node (Phase 1):
 * Uses a resilient LLM setup (with fallbacks) to generate a logical ER diagram
 * based on the user's scenario. Uses a purely structural Zod schema (AgentDiagramSchemaBase)
 * so that LLM output is not prematurely blocked by strict validation rules.
 * If previous errors exist, it feeds them back into the prompt for self-correction.
 *
 * @param state - The current state of the LangGraph agent
 * @returns Partial state update containing the generated jsonSchema or null on failure
 */
const generateNode = async (state: typeof AgentState.State) => {
  console.log(`[generateNode] Generating ER diagram...`);

  const structuredLlm = getResilientStructuredModel(AgentDiagramSchemaBase);

  const prompt = `You are a senior database architect.
Your task is to generate a logical ER diagram for this scenario: "${state.scenario}".

CRITICAL RULE: DO NOT use ANY of the following SQL reserved keywords for entity or attribute names:
${Array.from(SQL_RESERVED_WORDS).join(", ")}

Return your assessment matching the requested JSON schema perfectly.`;

  try {
    const response = await structuredLlm.invoke(prompt);
    return {
      jsonSchema: response,
    };
  } catch (error: any) {
    console.error(`[Error] generateNode LLM failure:`, error.message);
    // Return null schema. The schemaCritic will catch this and log the failure.
    return { jsonSchema: null };
  }
};

// 2. The schemaCritic Node
/**
 * Schema Critic Node (Phase 1):
 * Validates the raw JSON schema generated by the LLM using both structural Zod rules
 * (AgentDiagramSchema) and custom relational logic (e.g., primary keys, reserved words).
 * Accumulates all errors so the LLM can fix them in a single pass.
 *
 * @param state - The current state containing the raw jsonSchema
 * @returns Partial state update with validation status and any accumulated schemaErrors
 */
const schemaCriticNode = async (state: typeof AgentState.State) => {
  console.log(`[schemaCriticNode] Checking jsonSchema.`);
  const rawSchema = state.jsonSchema;

  if (!rawSchema) {
    return {
      schemaErrors: ["Schema generation failed. The LLM returned null."],
      isSchemaValid: false,
      schemaFixRetries: state.schemaFixRetries + 1,
    };
  }

  const newErrors: string[] = [];

  // ==========================================
  // 1. ZOD VALIDATION (Native Error Formatting)
  // ==========================================
  const parsed = AgentDiagramSchema.safeParse(rawSchema);

  if (!parsed.success) {
    // 🌟 THE FIX: Using Zod's native prettifyError for optimal LLM context
    const prettyErrors = z.prettifyError(parsed.error);

    // We push this as a single, highly readable block for the LLM prompt
    newErrors.push(`Schema Format Errors:\n${prettyErrors}`);
  }

  // ==========================================
  // 2. RELATIONAL VALIDATION (Cross-table logic)
  // ==========================================
  // We run this even if Zod fails so the LLM gets ALL errors in a single loop iteration.
  const entityNames = new Set(rawSchema.entities.map((e) => e.name));

  // adds up the errors for a single schemaCritic
  for (const entity of rawSchema.entities) {
    // Check for Primary Keys
    const hasPK = entity.attributes.some((attr) => attr.isPrimaryKey);
    if (!hasPK) {
      newErrors.push(
        `Relational Error: Entity '${entity.name}' is missing a Primary Key.`,
      );
    }

    // Check for Duplicate Column Names within the same entity
    const colNames = new Set<string>();
    for (const attr of entity.attributes) {
      if (colNames.has(attr.name)) {
        newErrors.push(
          `Relational Error: Entity '${entity.name}' has duplicate column '${attr.name}'.`,
        );
      }
      colNames.add(attr.name);
    }
  }

  // Ensure relationships point to valid entities
  for (const rel of rawSchema.relationships) {
    if (!entityNames.has(rel.sourceEntity)) {
      newErrors.push(
        `Relationship Error: Source Entity '${rel.sourceEntity}' does not exist. Did you mean to connect it to an existing table?`,
      );
    }
    if (!entityNames.has(rel.targetEntity)) {
      newErrors.push(
        `Relationship Error: Target Entity '${rel.targetEntity}' does not exist. Did you mean to connect it to an existing table?`,
      );
    }

    // Optional but recommended: Prevent self-referencing relationship loops if not supported by your UI
    if (rel.sourceEntity === rel.targetEntity) {
      newErrors.push(
        `Relationship Error: Entity '${rel.sourceEntity}' cannot have a relationship with itself in this canvas setup.`,
      );
    }
  }

  // ==========================================
  // 3. FINAL ROUTING DECISION
  // ==========================================

  // no Errors generated in this schemaCritic execution
  if (newErrors.length === 0) {
    /*schemaFixRetries stays same*/
    return { isSchemaValid: true, schemaErrors: [] };
  }

  // erros generated in this schemaCritic execution
  return {
    schemaErrors: newErrors,
    isSchemaValid: false,
    schemaFixRetries: state.schemaFixRetries + 1,
  };
};

// 3. The Router (Circuit Breaker Added, stop after 3 failures)
/**
 * Router Function for Phase 1:
 * Determines the next step in the LangGraph workflow based on the Critic's validation.
 * Includes a circuit breaker to prevent infinite loops (stops after 3 failures).
 *
 * @param state - The current state of the LangGraph agent
 * @returns The name of the next node ("compile" or "generator") or END
 */
const routeAfterschemaCritic = (state: typeof AgentState.State) => {
  if (state.isSchemaValid) {
    console.log(`[SchemaRouter] Schema valid. Routing to compilerNode.`);
    return "compile";
  }

  // THE CIRCUIT BREAKER: Stop the infinite loop if we've failed 3 times
  if (state.schemaFixRetries >= 3) {
    console.warn(
      `[SchemaRouter] Circuit Breaker triggered. Max retries hit. Routing to END.`,
    );
    return END;
  }

  // less than 3 retries => route to schemaFixer
  console.log(`[SchemaRouter] Schema invalid. Routing to schemaFixer.`);
  return "schemaFixer";
};

// 4. The Schema Fixer Node
/**
 * Schema Fixer Node (Phase 1):
 * If the Schema Critic finds logical or structural errors (like reserved keywords or missing PKs),
 * this node surgically fixes the JSON schema without generating everything from scratch.
 *
 * @param state - The current state containing the flawed jsonSchema and schemaErrors
 * @returns Partial state update with the fixed jsonSchema
 */
const schemaFixerNode = async (state: typeof AgentState.State) => {
  console.log(
    `[schemaFixerNode] Fixing JSON Schema errors (Attempt ${state.schemaFixRetries + 1}/3)...`,
  );

  // no jsonSchema found => move to [END] with error or loop to generate
  if (!state.jsonSchema || state.schemaErrors.length === 0) {
    return {};
  }

  const structuredLlm = getResilientStructuredModel(AgentDiagramSchemaBase);

  const prompt = `You are an expert Database Architect and Schema Fixer.
The following JSON ER diagram schema contains logical errors or uses SQL reserved keywords.
Your ONLY job is to explore the logic carefully and fix ALL the errors simultaneously so the schema perfectly passes validation.

CRITICAL RULES:
1. ONLY fix the errors listed. Do not rewrite the entire schema structure unnecessarily.
2. If an entity or attribute uses an SQL reserved keyword (e.g., USER, ORDER), rename it to a non-reserved equivalent (e.g., APP_USER, CUSTOMER_ORDER) and make sure you also update any relationships that reference it!
3. DO NOT use ANY of the following SQL reserved keywords for entity or attribute names:
${Array.from(SQL_RESERVED_WORDS).join(", ")}

Here are the Errors side-by-side with the flawed JSON schema:

[ERRORS TO FIX]
${state.schemaErrors.join("\n")}

[FLAWED JSON SCHEMA]
${JSON.stringify(state.jsonSchema, null, 2)}
`;

  try {
    const response = await structuredLlm.invoke(prompt);
    return {
      jsonSchema: response,
      schemaErrors: [], // Clear errors on success to let critic re-evaluate cleanly
    };
  } catch (error: any) {
    console.error(`[schemaFixerNode Error] LLM failure:`, error.message);
    return {};
  }
};

// PHASE 2:

import { generateSQL } from "@/lib/sqlGenerator";
import { generatePrisma } from "@/lib/prismaGenerator";
// Note: We don't need compileDiagramState anymore, because the AI already gave us the final logical shape(array of entityies with each entity containing an array of all its attributes + relnpEdges[])!

/**
 * Adapter Pattern for V1 Compatibility:
 * Transforms the clean AI-generated JSON schema into the legacy V1 React Flow format
 * (`compiledEntities` and `edges`). This allows reuse of the existing, battle-tested
 * SQL/Prisma generators without having to rewrite them.
 * Wrapped in `traceable` to send execution telemetry to LangSmith.
 *
 * @param schema - The validated JSON schema from Phase 1
 * @returns An object containing `compiledEntities` and `edges` arrays
 */
const adaptSchemaForV1 = traceable(
  (schema: any) => {
    // 1. Mock(copy) the compiledEntities array
    const compiledEntities = schema.entities.map((entity: any) => {
      // Find the primary key to satisfy V1's getPKDetails
      const pkAttr = entity.attributes.find((a: any) => a.isPrimaryKey);

      return {
        id /*id of entity*/: entity.name, // We use the name as the ID so edges can easily connect
        data: {
          label: entity.name,
          primaryKey: pkAttr ? pkAttr.name : "id",
        },
        attributes: entity.attributes.map((attr: any) => ({
          id: attr.name,
          name: attr.name,
          dataType: attr.dataType,
          size: attr.size,
          attributeType: attr.attributeType,
          isNotNull: attr.isNotNull,
          isUnique: attr.isUnique,
          data: { label: attr.name }, // V1 fallback
        })),
        foreignKeys: [], // preProcessRelationships needs this initialized
      };
    });

    // 2. Mock the edges array
    const edges = schema.relationships.map((rel: any, index: number) => {
      // Split "1:N" into source="1" and target="N"
      const maxCardinality = rel.maxCardinality || "1:N";
      const minCardinality = rel.minCardinality || "1:1";
      const [sourceMax, targetMax] = maxCardinality.split(":");
      const [sourceMin, targetMin] = minCardinality.split(":");

      return {
        id: `rel_${index}`,
        source: rel.sourceEntity, // Matches the entity.name (which we set as id above)
        target: rel.targetEntity,
        type: "relationship",
        data: {
          label: rel.label,
          sourceMaximumCardinality: sourceMax,
          targetMaximumCardinality: targetMax,
          sourceMinimumCardinality: sourceMin,
          targetMinimumCardinality: targetMin,
        },
      };
    });

    return { compiledEntities, edges };
  },
  {
    name: "adaptSchemaForV1",
    run_type: "chain", // must be one of: "tool", "chain", "llm", "retriever", "embedding", "prompt", "parser".
  },
) as (schema: any) => Promise<{ compiledEntities: any[]; edges: any[] }>;

// 1. The Compiler Node
/**
 * Compiler Node (Phase 2):
 * Takes the perfectly validated JSON schema, adapts it to the V1 format,
 * and passes it to the legacy code generators (SQL or Prisma) based on the chosen dialect.
 *
 * @param state - The current state containing the validated jsonSchema and chosen dialect
 * @returns Partial state update with the generatedSql and any scriptErrors
 */
const compilerNode = async (state: typeof AgentState.State) => {
  console.log(`[compilerNode] Compiling jsonSchema into v-1 script`);

  const schema = state.jsonSchema;

  if (!schema) {
    return {
      scriptErrors: [
        "[CompilerNode Error]: No valid JSON schema provided from Phase 1.",
      ],
    };
  }

  try {
    // Step 1: Adapt the clean AI JSON into V1's expected format
    const { compiledEntities, edges } = await adaptSchemaForV1(schema);

    // Step 2: Pass it to your existing, untouched V1 SQL Generator
    // We use the dialect stored in the new state definition
    let finalScript = ``;

    if (state.dialect === "prisma")
      finalScript = generatePrisma(compiledEntities, edges);
    else
      finalScript = generateSQL(
        compiledEntities,
        edges,
        state.dialect || "mysql",
      );

    return {
      generatedSql: finalScript,
      scriptErrors: [], // Clear errors on success
    };
  } catch (error: any) {
    // Catch any crashes (e.g., topological sort failing on weird input)
    return {
      scriptErrors: [`CompilerNode Crashed: ${error}`],
    };
  }
};

// 2. The Semantic Refiner Node
/**
 * Semantic Refiner Node (Phase 3):
 * Takes the raw, compiled SQL script (which may contain robotic, repetitive naming
 * from the V1 generator like 'student_student_id') and uses an LLM to semantically
 * refine the column/variable names into natural conventions.
 * **Does not alter the structural integrity or logic of the SQL.**
 *
 * @param state - The current state containing {generatedSql from v1}
 * @returns Partial state update overwriting generatedSql with the refined version
 */
const semanticRefinerNode = async (
  state: typeof AgentState.State,
): Promise<Partial<typeof AgentState.State>> => {
  console.log(`[semanticRefinerNode] Refining compiled SQL script...`);

  if (!state.generatedSql) {
    return {
      scriptErrors: [
        "[SemanticRefiner Error]: No generated SQL from v1 to refine.",
      ],
    };
  }

  let prompt = `You are a smart Database Naming Convention Refiner. Review the following script.
Your ONLY job is to clean up robotic, repetitive table, variable, and column names generated by a legacy compiler. 
You must pick meaningful, natural names according to the 'data structure' and 'data types'.

EXAMPLES OF BAD TO GOOD NAMING:
- Pluralize relation arrays: 'sends_messages' -> 'sentMessages', 'sends_userrs' -> 'senders'
- Simplify robotic junction tables: 'USERR_SENDS_MESSAGE' -> 'USER_MESSAGE_SENDER' (or something meaningful)
- Simplify redundant column names: 'userr_u_id' -> 'user_id', 'student_student_id' -> 'student_id'

CRITICAL RULES:
1. DO NOT change the data types, foreign key constraints, primary keys, or structural execution logic.
2. DO NOT use ANY of the following SQL reserved keywords for table or column names:
${Array.from(SQL_RESERVED_WORDS).join(", ")}
3. DO NOT wrap the output in markdown \`\`\` blocks. Output ONLY the pure SQL/Prisma string.

SCRIPT TO REFINE:
${state.generatedSql}
`;

  try {
    const response = await resilientModel.invoke(prompt);
    let refinedScript = response.content.toString().trim();

    // Clean up potential markdown blocks if the LLM ignores instructions
    if (refinedScript.startsWith("\`\`\`")) {
      const lines = refinedScript.split("\n");
      lines.shift();
      if (lines[lines.length - 1].startsWith("\`\`\`")) {
        lines.pop(); // removes last line
      }
      refinedScript = lines.join("\n").trim();
    }

    return { generatedSql: refinedScript, scriptErrors: [] };
  } catch (error: any) {
    console.error(`[SemanticRefiner Error] LLM failure:`, error.message);
    // On failure, gracefully fallback to the original generated SQL from v-1
    return {
      scriptErrors: [
        `[SemanticRefiner Warning]: Failed to refine script: ${error.message}`,
      ],
      isVersion1Sql: true,
    };
  }
};

// 3. The Script Critic Node
/**
 * Script Critic Node (Phase 3):
 * A final check to ensure the generated SQL syntax is valid and execution order is correct
 * (handling cyclic foreign keys). If errors are found, it routes to the Script Fixer.
 *
 * @param state - The current state containing generatedSql
 * @returns Partial state update with script validity and any errors
 */
const scriptCriticNode = async (
  state: typeof AgentState.State,
): Promise<Partial<typeof AgentState.State>> => {
  console.log(
    `[scriptCriticNode] Validating SQL execution order and syntax...`,
  );

  // no generatedSql received!
  if (!state.generatedSql) {
    return {
      isScriptValid: false,
      scriptErrors: ["No SQL script generated."],
      scriptFixRetries: state.scriptFixRetries + 1,
    };
  }

  // version 1 sql is not guaranteed to be correct !!
  if (state.isVersion1Sql) {
    console.log(
      `[scriptCriticNode] Got sql 'without semantic refinement' from version 1 generator`,
    );
  }

  const criticLlm = getResilientStructuredModel(ScriptValidationSchema);

  const prompt = `You are a strict Database Architect and Code Reviewer. 
Review the following ${state.dialect || "SQL"} script meticulously for structural and logical errors.

WHAT TO LOOK FOR:
1. Syntax validity: Ensure completely valid ${state.dialect || "SQL"} syntax.
2. Execution Order / Cyclic Dependencies: Parent tables MUST be created BEFORE child tables that reference them via Foreign Keys. 
3. Missing constraints or dangling references.

SCRIPT TO REVIEW:
${state.generatedSql}

Analyze the script deeply. If it has errors, output them clearly. Return your assessment matching the requested JSON schema perfectly.`;

  // wrap llm invokation in try-catch
  try {
    const response = await criticLlm.invoke(prompt);

    // attach errors provided from llm
    return {
      isScriptValid: response.isValid, // may be not valid
      scriptErrors: response.errors,
      scriptFixRetries: response.isValid
        ? state.scriptFixRetries
        : state.scriptFixRetries + 1,
      isVersion1Sql: false, // response may be valid, then llm made changes to v-1 sql, no v1 sql anymore
    };
  } catch (error: any) {
    console.error(`[scriptCriticNode Error] LLM failure:`, error.message);
    // On critic failure, let the version-1's sql go forward (with or without semantic refinement)
    return {
      isScriptValid: true,
      scriptErrors: [],
      isVersion1Sql: true,
    };
  }
};

// 4. The Script Router
/**
 * Router Function for Phase 3:
 * Determines if the script is production-ready or needs to loop to the scriptFixer.
 * Includes a circuit breaker to prevent infinite loops (stops after 3 failures).
 */
const routeAfterScriptCritic = (state: typeof AgentState.State) => {
  if (state.isScriptValid) {
    console.log(`[ScriptRouter] Script valid. Routing to END.`);
    return END;
  }

  if (state.isVersion1Sql) {
    console.log(`[ScriptRouter] Got sql from version 1 generator`);
  }

  // circuit breaker checks the number of times we looped back to the fixer
  if (state.scriptFixRetries >= 3) {
    console.warn(
      `[ScriptRouter] Script Circuit Breaker triggered. Max retries(3) hit. Routing to END.`,
    );
    return END;
  }

  console.log(`[ScriptRouter] Script invalid. Routing back to scriptFixer.`);
  return "scriptFixer";
};

// 5. The Script Fixer Node
/**
 * Script Fixer Node (Phase 3):
 * If the Script Critic finds execution order or syntax errors, this node is called.
 * It takes the broken script and the critic's errors, and uses an LLM to surgically fix them
 * (e.g., resolving cyclic foreign keys, or fixing typos).
 *
 * @param state - The current state containing generatedSql and scriptErrors
 * @returns Partial state update with the fixed generatedSql
 */
const scriptFixerNode = async (
  state: typeof AgentState.State,
): Promise<Partial<typeof AgentState.State>> => {
  console.log(
    `[scriptFixerNode] Fixing compiled SQL script based on criticNode's feedback (Attempt ${state.scriptFixRetries + 1}/3)...`,
  );

  // auto goes to END if no generateSQL or no scriptErrors
  if (!state.generatedSql || state.scriptErrors.length === 0) {
    return {};
  }

  const prompt = `You are an expert Database Architect and Code Fixer.
The following ${state.dialect || "SQL"} script contains structural, syntax, or execution order errors.
Your ONLY job is to explore the logic carefully and fix ALL the errors simultaneously so the script executes perfectly. Do not be lazy. You must address every error listed.

CRITICAL RULES:
1. DO NOT change the semantic names of the tables or columns.
2. DO NOT use ANY of the following SQL reserved keywords for table or column names:
${Array.from(SQL_RESERVED_WORDS).join(", ")}
3. DO NOT wrap the output in markdown \`\`\` blocks. Output ONLY the pure corrected script string.

Here are the Errors side-by-side with the Script:

[ERRORS TO FIX]
${state.scriptErrors.join("\n")}

[SCRIPT TO FIX]
${state.generatedSql}
`;

  try {
    const response = await resilientModel.invoke(prompt);
    let fixedScript = response.content.toString().trim();

    // Clean up potential markdown blocks if the LLM ignores instructions
    if (fixedScript.startsWith("\`\`\`")) {
      const lines = fixedScript.split("\n");
      lines.shift();
      if (lines[lines.length - 1].startsWith("\`\`\`")) {
        lines.pop(); // removes last line
      }
      fixedScript = lines.join("\n").trim();
    }

    return { generatedSql: fixedScript, scriptErrors: [] };
  } catch (error: any) {
    console.error(`[scriptFixerNode Error] LLM failure:`, error.message);
    // On failure, return the same script so the circuit breaker eventually kicks in
    return {
      scriptErrors: [
        `[ScriptFixer Warning]: Failed to fix script: ${error.message}`,
      ],
    };
  }
};

// 6. Assemble the LangGraph Workflow
const workflow = new StateGraph(AgentState)
  .addNode("generator", generateNode)
  .addNode("schemaCritic", schemaCriticNode)
  .addNode("schemaFixer", schemaFixerNode)
  .addNode("compile", compilerNode)
  .addNode("semanticRefine", semanticRefinerNode)
  .addNode("scriptCritic", scriptCriticNode)
  .addNode("scriptFixer", scriptFixerNode)

  .addEdge(START, "generator")
  .addEdge("generator", "schemaCritic")
  .addConditionalEdges("schemaCritic", routeAfterschemaCritic, {
    compile: "compile",
    schemaFixer: "schemaFixer",
    __end__: END,
  })
  .addEdge("schemaFixer", "schemaCritic")
  .addEdge("compile", "semanticRefine")
  .addEdge("semanticRefine", "scriptCritic")
  .addConditionalEdges("scriptCritic", routeAfterScriptCritic, {
    scriptFixer: "scriptFixer",
    __end__: END,
  })
  .addEdge("scriptFixer", "scriptCritic");

// Compile into a runnable agent
export const erArchitectAgent = workflow.compile();
